version: "3"
services:
  user_service:
    image: "quay.io/danielmunro/otto-user-service:latest"
    container_name: "user_service"
    ports:
      - "8080:8080"
  community_service:
    image: "quay.io/danielmunro/otto-community-service:latest"
    container_name: "community_service"
    ports:
      - "8081:8081"
#  image_service:
#    image: "quay.io/danielmunro/otto-image-service:latest"
#    container_name: "image_service"
#    ports:
#      - "8082:8082"
#  ui:
#    image: "quay.io/danielmunro/otto-ui:latest"
#    container_name: "ui"
#    ports:
#      - "8083:8083"
  api_gw:
    image: "quay.io/danielmunro/otto-api-gw:latest"
    container_name: "api_gw"
    ports:
      - "8000:8000"
  db:
    image: "postgres"
    container_name: "my_postgres"
    env_file:
      - .env
    ports:
      - "54321:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  zookeeper:
    image: wurstmeister/zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: confluentinc/cp-kafka:5.2.1
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "users:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
